# This is a config for E2B sandbox template.
# You can use template ID (czvy0m34fw7h8xbd6ihp) or template name (vibe-nextjs-student) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-student") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-student") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-student')

team_id = "52e96e6b-8e7a-42e5-a488-1411cc59d8b4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-student"
template_id = "czvy0m34fw7h8xbd6ihp"
